package com.databuff.digitalexpert.dao.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    INVALID_REQUEST(4000001, "INVALID_REQUEST"),
    SKILL_PACKAGE_NOT_FOUND(4001001, "SKILL_PACKAGE_NOT_FOUND"),
    INVALID_SKILL_PACKAGE(4001002, "INVALID_SKILL_PACKAGE"),
    SKILL_MD_MISSING_NAME_OR_DESCRIPTION(4001003, "SKILL_MD_MISSING_NAME_OR_DESCRIPTION"),
    STATIC_PACKAGE_NOT_FOUND(4002001, "STATIC_PACKAGE_NOT_FOUND"),
    EXPERT_NOT_FOUND(4003001, "EXPERT_NOT_FOUND"),
    EXPERT_DISABLED(4003002, "EXPERT_DISABLED"),
    MCP_BINDING_INVALID(4003003, "MCP_BINDING_INVALID"),
    PACKAGE_PATH_MISSING(4003004, "PACKAGE_PATH_MISSING"),
    EXPERT_PACKAGE_NOT_READY(4003005, "EXPERT_PACKAGE_NOT_READY"),
    ACTIVE_RELEASE_TASK_EXISTS(4003006, "ACTIVE_RELEASE_TASK_EXISTS"),
    RELEASE_TASK_NOT_FOUND(4003007, "RELEASE_TASK_NOT_FOUND"),
    DUPLICATE_RESOURCE(4003008, "DUPLICATE_RESOURCE"),
    INTERNAL_ERROR(5000001, "INTERNAL_ERROR");

    private final int code;
    private final String message;
}

